version: 2

sources:
  - name: raw
    database: SALES_DB
    schema: RAW
    tables:
      - name: orders
      - name: customers
      - name: products

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null